name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-linux:
    name: Build Linux
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@master
    - name: Install gtk3
      run: sudo apt-get install build-essential libgtk-3-dev
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3

    - name: Build
      run: go build -o ./tray_linux_release -ldflags "-s -w" tray.go
