name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-16.04
            binary: tray_linux_release
          - os: windows-latest
            binary: tray_windows_release.exe
    steps:
    - uses: actions/checkout@master

    - name: Install gtk3
      if: ${{ matrix.os == 'ubuntu-16.04' }}
      run: sudo apt-get install libgtk-3-dev libappindicator3-dev

    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3

    - name: Build
      run: go build -o ${{ matrix.binary }} -ldflags "-s -w" tray.go

    - name: Upload a Release Asset
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # The URL for uploading assets to the release
        upload_url: https://uploads.github.com/repos/felixhao28/systray-portable/releases/33386051/assets{?name,label}
        # The path to the asset you want to upload
        asset_path: ${{ matrix.binary }}
        # The name of the asset you want to upload
        asset_name: ${{ matrix.binary }}
        # The content-type of the asset you want to upload. See the supported Media Types here: https://www.iana.org/assignments/media-types/media-types.xhtml for more information
        asset_content_type: application/octet-stream
