name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-linux:
    name: Build Linux
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@master
    - name: Install gtk3
      run: sudo apt-get install libgtk-3-dev libappindicator3-dev
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3

    - name: Build
      run: go build -o ./tray_linux_release -ldflags "-s -w" tray.go

    - name: Upload a Release Asset
      uses: actions/upload-release-asset@v1.0.2
      with:
        # The URL for uploading assets to the release
        upload_url: https://uploads.github.com/repos/felixhao28/systray-portable/releases/33386051/assets{?name,label}
        # The path to the asset you want to upload
        asset_path: https://api.github.com/repos/felixhao28/systray-portable/releases/33386051/assets
        # The name of the asset you want to upload
        asset_name: tray_darwin_release
        # The content-type of the asset you want to upload. See the supported Media Types here: https://www.iana.org/assignments/media-types/media-types.xhtml for more information
        asset_content_type: application/octet-stream
